import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Code Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navBar}>
        <ul>
          <li>Home</li>
          <li> About</li>
          <li>Contact</li>

        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Code Tech
        </h1>

        <p className={styles.description}>
          Blogs for Coders by Coders
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>Learn Next.js</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        By Salman
      </footer>
    </div>
  )
}
